apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bhargav-deploy
  name: bhargav-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bhargav-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: bhargav-deploy
    spec:
      containers:
      - image: bhargavakulla/app
        name: bhargavakulla
        resources: {}
status: {}
