apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trial
  name: trial
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trial
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: trial
    spec:
      containers:
      - image: samimmondal/sample
        name: samimmondal
        resources: {}
status: {}
